# Generated by Django 3.2.4 on 2021-06-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_visit_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.CharField(max_length=255),
        ),
    ]
