# Generated by Django 3.2.4 on 2021-06-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_visit_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_relation', to='registry.patients'),
        ),
    ]
